apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../base
  - sealedsecret-bot-token.yaml

images:
  - name: fedoteh/telegram-boty
    newTag: "v0.1.1"