---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot-secrets
  namespace: apps
spec:
  encryptedData:
    BOT_TOKEN: AgC5df5eRKKxQC7UWnHVdMnABbuW3x282INJ8TNEeLmRYBefH3QP7aKI+BrCD/nhu2n2b+fD+mi1jGnSonYrjkmpO+VA8bgeFHmEwd2xRGy32w+e7iGzJkLW+KRXwiA/gkNjqrykmmuwxe7wRdPg003XHUdhR2cBbXs4oXrJx13EmiyuVdTZYpq6C94uD2H1c95ub/ghMATi1vfn12WNe4DthNrjlLvMOkXeq81cX89FqwXiMviLJQ0BwwaynvfOOFQVf8RK+Cyeenzk6oB/ih1ADEih9k3DBxHl1O9TXylNZW6PvaZnRkfzhSreZFpZcTfjXaINdgVWd7UoFDEBUKlKYur9m0UnVMGLK/HcXFSBAq61FjicludFMFWAojFoyRyTNUs191TAK8ocqVBd9zAsplfak1NxyHFq1XN4Ax5pPvGyo6NB2jCQjSTngdrxTs5jjSk0IxIfCYuwSPL4mAegCsAlMt9hvyqRoVPmmymyESCxxvIcaVOqoxSF17JhJD2vwhtYEm7GDCP9iJpfzc3he6wT/e7QA6ayTdGY3scA2I0kqxPDf9V5zwZVi9hEcshsjZ25Oa9CHZicp26KmnElc3uf8lXQJw6q4UdBEBBeq5CbFsKWgH4iajoAiRgv5N+Y+fftXv7om2REQh/NGf2zl9PhIp6ALjggNVjJBj2ba2GnvW0XPNWUSUc0Dh0xd/IFCgrH3lG+L8wLf0qdgvdJZowPcVzBSMr3CzMNHz8sc0YJ0mDB1UEjYIZNzGsU
  template:
    metadata:
      name: telegram-bot-secrets
      namespace: apps
